// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name, type) VALUES ($1, $2, $3)
RETURNING id, name, type, setting_value, created_at, updated_at
`

type CreateAccountParams struct {
	ID   uuid.UUID
	Name string
	Type string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.ID, arg.Name, arg.Type)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.SettingValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, type, created_at, updated_at FROM accounts WHERE id = $1
`

type GetAccountRow struct {
	ID        uuid.UUID
	Name      string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvestmentAnnualRate = `-- name: GetInvestmentAnnualRate :one
SELECT setting_value FROM accounts WHERE name = 'system.investment_annual_rate'
`

func (q *Queries) GetInvestmentAnnualRate(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getInvestmentAnnualRate)
	var setting_value sql.NullString
	err := row.Scan(&setting_value)
	return setting_value, err
}
