// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name, type) VALUES ($1, $2, $3)
RETURNING id, name, type, client_id, created_at, updated_at
`

type CreateAccountParams struct {
	ID   uuid.UUID
	Name string
	Type string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.ID, arg.Name, arg.Type)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, type, client_id, created_at, updated_at FROM accounts WHERE name = $1
`

func (q *Queries) GetAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, type, client_id, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountDetails = `-- name: GetAccountDetails :one
SELECT a.id, a.name, a.type, c.id AS client_id FROM accounts a
JOIN clients c ON a.client_id = c.id
WHERE a.name = $1
`

type GetAccountDetailsRow struct {
	ID       uuid.UUID
	Name     string
	Type     string
	ClientID uuid.UUID
}

func (q *Queries) GetAccountDetails(ctx context.Context, name string) (GetAccountDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountDetails, name)
	var i GetAccountDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ClientID,
	)
	return i, err
}

const getCapitalAccount = `-- name: GetCapitalAccount :one
SELECT id FROM accounts WHERE name = 'Capital Account' LIMIT 1
`

func (q *Queries) GetCapitalAccount(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getCapitalAccount)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
