// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, client_type, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
