// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getClientByReference = `-- name: GetClientByReference :one
SELECT id, name, client_type FROM clients WHERE id = $1
`

type GetClientByReferenceRow struct {
	ID         uuid.UUID
	Name       string
	ClientType string
}

func (q *Queries) GetClientByReference(ctx context.Context, id uuid.UUID) (GetClientByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getClientByReference, id)
	var i GetClientByReferenceRow
	err := row.Scan(&i.ID, &i.Name, &i.ClientType)
	return i, err
}
