// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, client_type FROM clients WHERE id = $1
`

type GetClientByIDRow struct {
	ID         uuid.UUID
	Name       string
	ClientType string
}

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (GetClientByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i GetClientByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.ClientType)
	return i, err
}
