// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, account_id, transaction_id, amount, type, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, transaction_id, amount, type, created_at, updated_at
`

type CreateEntryParams struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	TransactionID uuid.UUID
	Amount        int64
	Type          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.ID,
		arg.AccountID,
		arg.TransactionID,
		arg.Amount,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.Amount,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT id, account_id, transaction_id, amount, type, created_at, updated_at FROM entries WHERE account_id = $1
`

func (q *Queries) GetEntries(ctx context.Context, accountID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntries, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionID,
			&i.Amount,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
