// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (
    id,
    client_id,
    principal_initial,
    principal_current,
    annual_rate,
    status,
    accrued_interest,
    next_accrual_at,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $2,
    0.3,
    'active',
    0,
    $3,
    NOW(),
    NOW()
)
RETURNING id, client_id, principal_initial, principal_current, annual_rate, status, accrued_interest, next_accrual_at, last_accrual_at, created_at, updated_at
`

type CreateInvestmentParams struct {
	ClientID         uuid.UUID
	PrincipalInitial int64
	NextAccrualAt    time.Time
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRowContext(ctx, createInvestment, arg.ClientID, arg.PrincipalInitial, arg.NextAccrualAt)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PrincipalInitial,
		&i.PrincipalCurrent,
		&i.AnnualRate,
		&i.Status,
		&i.AccruedInterest,
		&i.NextAccrualAt,
		&i.LastAccrualAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, client_id, principal_initial, principal_current, annual_rate, status, accrued_interest, next_accrual_at, last_accrual_at, created_at, updated_at FROM investments WHERE id = $1
`

func (q *Queries) GetInvestmentByID(ctx context.Context, id uuid.UUID) (Investment, error) {
	row := q.db.QueryRowContext(ctx, getInvestmentByID, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PrincipalInitial,
		&i.PrincipalCurrent,
		&i.AnnualRate,
		&i.Status,
		&i.AccruedInterest,
		&i.NextAccrualAt,
		&i.LastAccrualAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvestmentAccrual = `-- name: UpdateInvestmentAccrual :exec
UPDATE investments
SET accrued_interest = accrued_interest + $1, 
next_accrual_at = $2, 
last_accrual_at = $3,
updated_at = $4
WHERE id = $5
`

type UpdateInvestmentAccrualParams struct {
	AccruedInterest int64
	NextAccrualAt   time.Time
	LastAccrualAt   sql.NullTime
	UpdatedAt       time.Time
	ID              uuid.UUID
}

func (q *Queries) UpdateInvestmentAccrual(ctx context.Context, arg UpdateInvestmentAccrualParams) error {
	_, err := q.db.ExecContext(ctx, updateInvestmentAccrual,
		arg.AccruedInterest,
		arg.NextAccrualAt,
		arg.LastAccrualAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
