// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investment_accruals.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccrualRecord = `-- name: CreateAccrualRecord :one
INSERT INTO investment_accruals (
    id,
    investment_id,
    amount,
    accrual_timestamp
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
RETURNING id, investment_id, accrual_timestamp, amount, created_at
`

type CreateAccrualRecordParams struct {
	InvestmentID     uuid.UUID
	Amount           int64
	AccrualTimestamp time.Time
}

func (q *Queries) CreateAccrualRecord(ctx context.Context, arg CreateAccrualRecordParams) (InvestmentAccrual, error) {
	row := q.db.QueryRowContext(ctx, createAccrualRecord, arg.InvestmentID, arg.Amount, arg.AccrualTimestamp)
	var i InvestmentAccrual
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.AccrualTimestamp,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
