// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investment_withdrawal.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvestmentWithdrawal = `-- name: CreateInvestmentWithdrawal :one
INSERT INTO investment_withdrawals (
    investment_id,
    amount,
    notice_period_months,
    requested_at,
    eligible_at,
    status
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, investment_id, amount, notice_period_months, requested_at, eligible_at, status, created_at, updated_at
`

type CreateInvestmentWithdrawalParams struct {
	InvestmentID       uuid.UUID
	Amount             int64
	NoticePeriodMonths int32
	RequestedAt        time.Time
	EligibleAt         time.Time
	Status             string
}

func (q *Queries) CreateInvestmentWithdrawal(ctx context.Context, arg CreateInvestmentWithdrawalParams) (InvestmentWithdrawal, error) {
	row := q.db.QueryRowContext(ctx, createInvestmentWithdrawal,
		arg.InvestmentID,
		arg.Amount,
		arg.NoticePeriodMonths,
		arg.RequestedAt,
		arg.EligibleAt,
		arg.Status,
	)
	var i InvestmentWithdrawal
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.Amount,
		&i.NoticePeriodMonths,
		&i.RequestedAt,
		&i.EligibleAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEligibleWithdrawals = `-- name: ListEligibleWithdrawals :many
SELECT id, investment_id, amount, notice_period_months, requested_at, eligible_at, status, created_at, updated_at FROM investment_withdrawals
WHERE eligible_at <= NOW()
AND status = 'pending'
ORDER BY eligible_at ASC
`

func (q *Queries) ListEligibleWithdrawals(ctx context.Context) ([]InvestmentWithdrawal, error) {
	rows, err := q.db.QueryContext(ctx, listEligibleWithdrawals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentWithdrawal
	for rows.Next() {
		var i InvestmentWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.Amount,
			&i.NoticePeriodMonths,
			&i.RequestedAt,
			&i.EligibleAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
