// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, client_id, loan_number, product_type, status, principal_amount, outstanding_amount, created_at, updated_at
FROM loans WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id uuid.UUID) (Loan, error) {
	row := q.db.QueryRowContext(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LoanNumber,
		&i.ProductType,
		&i.Status,
		&i.PrincipalAmount,
		&i.OutstandingAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanByLoanNumber = `-- name: GetLoanByLoanNumber :one
SELECT id, client_id, loan_number, product_type, status, principal_amount, outstanding_amount, created_at, updated_at
FROM loans WHERE loan_number = $1
`

func (q *Queries) GetLoanByLoanNumber(ctx context.Context, loanNumber string) (Loan, error) {
	row := q.db.QueryRowContext(ctx, getLoanByLoanNumber, loanNumber)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LoanNumber,
		&i.ProductType,
		&i.Status,
		&i.PrincipalAmount,
		&i.OutstandingAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoansByClientID = `-- name: GetLoansByClientID :many
SELECT id, client_id, loan_number, product_type, status, principal_amount, outstanding_amount, created_at, updated_at
FROM loans WHERE client_id = $1 AND status = 'active'
`

func (q *Queries) GetLoansByClientID(ctx context.Context, clientID uuid.UUID) ([]Loan, error) {
	rows, err := q.db.QueryContext(ctx, getLoansByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LoanNumber,
			&i.ProductType,
			&i.Status,
			&i.PrincipalAmount,
			&i.OutstandingAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoanOutstandingAmount = `-- name: UpdateLoanOutstandingAmount :exec
UPDATE loans SET outstanding_amount = $1, updated_at = NOW() WHERE id = $2
`

type UpdateLoanOutstandingAmountParams struct {
	OutstandingAmount int64
	ID                uuid.UUID
}

func (q *Queries) UpdateLoanOutstandingAmount(ctx context.Context, arg UpdateLoanOutstandingAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateLoanOutstandingAmount, arg.OutstandingAmount, arg.ID)
	return err
}
