// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Client struct {
	ID         uuid.UUID
	Name       string
	ClientType string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Entry struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	TransactionID uuid.UUID
	Amount        int64
	Type          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Loan struct {
	ID                uuid.UUID
	ClientID          uuid.UUID
	LoanNumber        string
	ProductType       string
	Status            string
	PrincipalAmount   int64
	OutstandingAmount int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Transaction struct {
	ID        uuid.UUID
	Reference string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UnresolvedPayment struct {
	ID             uuid.UUID
	ClientRef      string
	Amount         int64
	PaymentChannel string
	ExternalID     string
	Reason         string
	CreatedAt      time.Time
	RawEvent       json.RawMessage
}
