// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID
	Name         string
	Type         string
	SettingValue sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Client struct {
	ID         uuid.UUID
	Name       string
	ClientType string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Entry struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	TransactionID uuid.UUID
	Amount        int64
	Type          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Investment struct {
	ID               uuid.UUID
	ClientID         uuid.UUID
	PrincipalInitial int64
	PrincipalCurrent int64
	AnnualRate       string
	Status           string
	AccruedInterest  int64
	NextAccrualAt    time.Time
	LastAccrualAt    sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type InvestmentAccrual struct {
	ID               uuid.UUID
	InvestmentID     uuid.UUID
	AccrualTimestamp time.Time
	Amount           int64
	CreatedAt        time.Time
}

type InvestmentWithdrawal struct {
	ID                 uuid.UUID
	InvestmentID       uuid.UUID
	Amount             int64
	NoticePeriodMonths int32
	RequestedAt        time.Time
	EligibleAt         time.Time
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Loan struct {
	ID                uuid.UUID
	ClientID          uuid.UUID
	LoanNumber        string
	ProductType       string
	Status            string
	PrincipalAmount   int64
	OutstandingAmount int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Transaction struct {
	ID        uuid.UUID
	Reference string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UnresolvedPayment struct {
	ID             uuid.UUID
	ClientRef      string
	Amount         int64
	PaymentChannel string
	ExternalID     string
	Reason         string
	CreatedAt      time.Time
	RawEvent       json.RawMessage
}
