// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Entry struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	TransactionID uuid.UUID
	Amount        int64
	Type          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Transaction struct {
	ID        uuid.UUID
	Reference string
	CreatedAt time.Time
	UpdatedAt time.Time
}
