// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_messages.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const claimPendingMessages = `-- name: ClaimPendingMessages :many
update outbox_messages
set status = 'processing',
locked_at = NOW(),
locked_by = $1,
updated_at = NOW()
where id in (
    select id from outbox_messages
    where status IN ('pending', 'failed') AND
    attempts < 5
ORDER BY created_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
)
RETURNING id, aggregate_type, aggregate_id, command_type, payload, status, attempts, locked_at, published_at, locked_by, last_error, created_at, updated_at
`

type ClaimPendingMessagesParams struct {
	LockedBy sql.NullString
	Limit    int32
}

func (q *Queries) ClaimPendingMessages(ctx context.Context, arg ClaimPendingMessagesParams) ([]OutboxMessage, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingMessages, arg.LockedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxMessage
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.CommandType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LockedAt,
			&i.PublishedAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxMessage = `-- name: CreateOutboxMessage :one
INSERT INTO outbox_messages (
    aggregate_type,
    aggregate_id,
    command_type,
    payload,
    status,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, 'pending', NOW(), NOW())
RETURNING id, aggregate_type, aggregate_id, command_type, payload, status, attempts, locked_at, published_at, locked_by, last_error, created_at, updated_at
`

type CreateOutboxMessageParams struct {
	AggregateType string
	AggregateID   uuid.UUID
	CommandType   string
	Payload       json.RawMessage
}

func (q *Queries) CreateOutboxMessage(ctx context.Context, arg CreateOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRowContext(ctx, createOutboxMessage,
		arg.AggregateType,
		arg.AggregateID,
		arg.CommandType,
		arg.Payload,
	)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LockedAt,
		&i.PublishedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMessageAsFailed = `-- name: MarkMessageAsFailed :exec
UPDATE outbox_messages
SET status = 'failed',
attempts = attempts + 1,
updated_at = NOW(),
last_error = $2,
locked_at = NULL,
locked_by = NULL
WHERE id = $1
`

type MarkMessageAsFailedParams struct {
	ID        uuid.UUID
	LastError sql.NullString
}

func (q *Queries) MarkMessageAsFailed(ctx context.Context, arg MarkMessageAsFailedParams) error {
	_, err := q.db.ExecContext(ctx, markMessageAsFailed, arg.ID, arg.LastError)
	return err
}

const markMessageAsPublished = `-- name: MarkMessageAsPublished :exec
UPDATE outbox_messages
SET status = 'published',
published_at = NOW(),
updated_at = NOW(),
last_error = NULL,
locked_at = NULL,
locked_by = NULL
WHERE id = $1
`

func (q *Queries) MarkMessageAsPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markMessageAsPublished, id)
	return err
}

const releaseStaleLocks = `-- name: ReleaseStaleLocks :exec
UPDATE outbox_messages
SET status = 'failed',
last_error = 'Dispatcher lock expired',
locked_at = NULL,
locked_by = NULL,
updated_at = NOW()
WHERE status = 'processing'
AND locked_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) ReleaseStaleLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, releaseStaleLocks)
	return err
}
