// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overpayment.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOverpayment = `-- name: CreateOverpayment :one
INSERT INTO overpayments (
    loan_id,
    external_id,
    amount,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    'pending',
    NOW(),
    NOW()
)
RETURNING id, loan_id, external_id, amount, status, created_at, updated_at
`

type CreateOverpaymentParams struct {
	LoanID     uuid.UUID
	ExternalID string
	Amount     int64
}

func (q *Queries) CreateOverpayment(ctx context.Context, arg CreateOverpaymentParams) (Overpayment, error) {
	row := q.db.QueryRowContext(ctx, createOverpayment, arg.LoanID, arg.ExternalID, arg.Amount)
	var i Overpayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.ExternalID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOverpaymentByLoanID = `-- name: GetOverpaymentByLoanID :one
SELECT id, loan_id, external_id, amount, status, created_at, updated_at FROM overpayments WHERE loan_id = $1
`

func (q *Queries) GetOverpaymentByLoanID(ctx context.Context, loanID uuid.UUID) (Overpayment, error) {
	row := q.db.QueryRowContext(ctx, getOverpaymentByLoanID, loanID)
	var i Overpayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.ExternalID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOverpaymentAmount = `-- name: UpdateOverpaymentAmount :exec
UPDATE overpayments SET amount = $1, updated_at = NOW() WHERE id = $2
`

type UpdateOverpaymentAmountParams struct {
	Amount int64
	ID     uuid.UUID
}

func (q *Queries) UpdateOverpaymentAmount(ctx context.Context, arg UpdateOverpaymentAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateOverpaymentAmount, arg.Amount, arg.ID)
	return err
}

const updateOverpaymentStatus = `-- name: UpdateOverpaymentStatus :exec
UPDATE overpayments SET status = $1, updated_at = NOW() WHERE id = $2
`

type UpdateOverpaymentStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateOverpaymentStatus(ctx context.Context, arg UpdateOverpaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOverpaymentStatus, arg.Status, arg.ID)
	return err
}
