// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_references.sql

package database

import (
	"context"
)

const createPaymentReference = `-- name: CreatePaymentReference :one
INSERT INTO payment_references (reference, entity_type)
VALUES ($1, $2 )
RETURNING id, reference, entity_type, created_at, updated_at
`

type CreatePaymentReferenceParams struct {
	Reference  string
	EntityType string
}

func (q *Queries) CreatePaymentReference(ctx context.Context, arg CreatePaymentReferenceParams) (PaymentReference, error) {
	row := q.db.QueryRowContext(ctx, createPaymentReference, arg.Reference, arg.EntityType)
	var i PaymentReference
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.EntityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentReference = `-- name: GetPaymentReference :one
SELECT id, reference, entity_type, created_at, updated_at
FROM payment_references
WHERE reference = $1
`

func (q *Queries) GetPaymentReference(ctx context.Context, reference string) (PaymentReference, error) {
	row := q.db.QueryRowContext(ctx, getPaymentReference, reference)
	var i PaymentReference
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.EntityType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
