// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, raw_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at
`

type CreatePaymentParams struct {
	IdempotencyKey string
	ExternalID     string
	Amount         int64
	PaymentType    string
	PhoneNumber    string
	ClientRef      string
	PaymentRef     string
	Destination    string
	RawEvent       json.RawMessage
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.IdempotencyKey,
		arg.ExternalID,
		arg.Amount,
		arg.PaymentType,
		arg.PhoneNumber,
		arg.ClientRef,
		arg.PaymentRef,
		arg.Destination,
		arg.RawEvent,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnresolvedPayments = `-- name: GetUnresolvedPayments :many
SELECT id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at FROM payments
WHERE status = 'unresolved'
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetUnresolvedPayments(ctx context.Context, limit int32) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getUnresolvedPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.ExternalID,
			&i.Amount,
			&i.PaymentType,
			&i.PhoneNumber,
			&i.ClientRef,
			&i.PaymentRef,
			&i.Destination,
			&i.Status,
			&i.ResolvedType,
			&i.ResolvingStartedAt,
			&i.RawEvent,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at FROM payments 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.ExternalID,
			&i.Amount,
			&i.PaymentType,
			&i.PhoneNumber,
			&i.ClientRef,
			&i.PaymentRef,
			&i.Destination,
			&i.Status,
			&i.ResolvedType,
			&i.ResolvingStartedAt,
			&i.RawEvent,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePayment = `-- name: ResolvePayment :exec
UPDATE payments
SET status = $2, resolved_type = $3, resolved_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type ResolvePaymentParams struct {
	ID           uuid.UUID
	Status       string
	ResolvedType sql.NullString
}

func (q *Queries) ResolvePayment(ctx context.Context, arg ResolvePaymentParams) error {
	_, err := q.db.ExecContext(ctx, resolvePayment, arg.ID, arg.Status, arg.ResolvedType)
	return err
}

const tryClaimPayment = `-- name: TryClaimPayment :one
UPDATE payments
SET STATUS = 'resolving', 
resolving_started_at = NOW(), updated_at = NOW()
WHERE idempotency_key = $1
AND (
	status = 'received'
	OR (
		status = 'resolving' AND
		resolving_started_at  <= NOW() - interval '20 seconds'
		)
	)
RETURNING id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at
`

// Check processing status of a payment
func (q *Queries) TryClaimPayment(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, tryClaimPayment, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryCompletePayment = `-- name: TryCompletePayment :one
UPDATE payments
SET STATUS = 'completed',
updated_at = NOW()
WHERE idempotency_key = $1
AND (
	status = 'resolving'
	)
RETURNING id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at
`

func (q *Queries) TryCompletePayment(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, tryCompletePayment, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryFailPayment = `-- name: TryFailPayment :one
UPDATE payments
SET STATUS = 'failed',
updated_at = NOW()
WHERE idempotency_key = $1
AND (
	status = 'resolving' AND
	resolving_started_at  <= NOW() - interval '20 seconds'
	)
RETURNING id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at
`

func (q *Queries) TryFailPayment(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, tryFailPayment, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryUnresolvePayment = `-- name: TryUnresolvePayment :one
UPDATE payments
SET STATUS = 'unresolved',
updated_at = NOW()
WHERE idempotency_key = $1
AND (
	status = 'resolving' 
)
Returning id, idempotency_key, external_id, amount, payment_type, phone_number, client_ref, payment_ref, destination, status, resolved_type, resolving_started_at, raw_event, created_at, resolved_at, updated_at
`

func (q *Queries) TryUnresolvePayment(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, tryUnresolvePayment, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ExternalID,
		&i.Amount,
		&i.PaymentType,
		&i.PhoneNumber,
		&i.ClientRef,
		&i.PaymentRef,
		&i.Destination,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvingStartedAt,
		&i.RawEvent,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
