// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unresolved_payments.sql

package database

import (
	"context"
	"encoding/json"
)

const createUnresolvedPayment = `-- name: CreateUnresolvedPayment :one
INSERT INTO unresolved_payments (client_ref, amount, payment_channel, external_id, reason, raw_event)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_ref, amount, payment_channel, external_id, reason, created_at, raw_event
`

type CreateUnresolvedPaymentParams struct {
	ClientRef      string
	Amount         int64
	PaymentChannel string
	ExternalID     string
	Reason         string
	RawEvent       json.RawMessage
}

func (q *Queries) CreateUnresolvedPayment(ctx context.Context, arg CreateUnresolvedPaymentParams) (UnresolvedPayment, error) {
	row := q.db.QueryRowContext(ctx, createUnresolvedPayment,
		arg.ClientRef,
		arg.Amount,
		arg.PaymentChannel,
		arg.ExternalID,
		arg.Reason,
		arg.RawEvent,
	)
	var i UnresolvedPayment
	err := row.Scan(
		&i.ID,
		&i.ClientRef,
		&i.Amount,
		&i.PaymentChannel,
		&i.ExternalID,
		&i.Reason,
		&i.CreatedAt,
		&i.RawEvent,
	)
	return i, err
}
