// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unresolved_payments.sql

package database

import (
	"context"
	"encoding/json"
)

const createUnresolvedPayment = `-- name: CreateUnresolvedPayment :exec
INSERT INTO unresolved_payments (client_ref, amount, payment_channel, external_id, reason, raw_event)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUnresolvedPaymentParams struct {
	ClientRef      string
	Amount         int64
	PaymentChannel string
	ExternalID     string
	Reason         string
	RawEvent       json.RawMessage
}

func (q *Queries) CreateUnresolvedPayment(ctx context.Context, arg CreateUnresolvedPaymentParams) error {
	_, err := q.db.ExecContext(ctx, createUnresolvedPayment,
		arg.ClientRef,
		arg.Amount,
		arg.PaymentChannel,
		arg.ExternalID,
		arg.Reason,
		arg.RawEvent,
	)
	return err
}
